import type { PrismaClient } from '../../../node_modules/.prisma/tenant-client/index.js';
import { getPdfExportAdapter } from '../../adapters/pdf-export/index.js';
import { auditLog } from '../../core/audit-logger.js';
import { NotFoundError } from '../../core/errors.js';
import type { AuthContext } from '../../types/auth.js';
import { readFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function loadTemplate(): string {
  try {
    const templatePath = path.resolve(__dirname, '../../templates/visit-summary.html');
    return readFileSync(templatePath, 'utf-8');
  } catch {
    return getDefaultTemplate();
  }
}

function getDefaultTemplate(): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Visit Summary</title>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
  h1 { color: #1a5276; border-bottom: 2px solid #1a5276; }
  .section { margin: 20px 0; }
  .label { font-weight: bold; color: #555; }
</style>
</head>
<body>
  <h1>CareMind AI — Visit Summary</h1>
  <div class="section">
    <p><span class="label">Patient:</span> {{PATIENT_NAME}}</p>
    <p><span class="label">Doctor:</span> {{DOCTOR_NAME}}</p>
    <p><span class="label">Date:</span> {{DATE}}</p>
  </div>
  <div class="section">
    <h2>Summary</h2>
    <p>{{CONTENT}}</p>
  </div>
  <div class="section">
    <p style="font-size: 11px; color: #888;">
      This document was generated by CareMind AI and reviewed by your healthcare provider.
      For questions, contact your clinic directly.
    </p>
  </div>
</body>
</html>`;
}

export async function generateVisitSummaryPdf(
  auth: AuthContext,
  tenantPrisma: PrismaClient,
  appointmentId: string,
): Promise<Buffer> {
  const appointment = await tenantPrisma.appointment.findUnique({
    where: { id: appointmentId },
    include: { patient: true, doctor: true },
  });

  if (!appointment || appointment.orgId !== auth.orgId) {
    throw new NotFoundError('Appointment not found');
  }

  const patientSummary = await tenantPrisma.aiOutput.findFirst({
    where: {
      appointmentId,
      type: 'patient_summary',
      status: { in: ['approved', 'edited'] },
    },
    orderBy: { reviewedAt: 'desc' },
  });

  if (!patientSummary) {
    throw new NotFoundError('Approved patient summary not available for this appointment');
  }

  const patientName = `${appointment.patient.firstName} ${appointment.patient.lastName}`;
  const doctorName = `Dr. ${appointment.doctor.firstName} ${appointment.doctor.lastName}`;
  const date = new Date(appointment.scheduledAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const template = loadTemplate();
  const html = template
    .replace('{{PATIENT_NAME}}', patientName)
    .replace('{{DOCTOR_NAME}}', doctorName)
    .replace('{{DATE}}', date)
    .replace('{{CONTENT}}', patientSummary.content.replace(/\n/g, '<br/>'));

  const pdfAdapter = getPdfExportAdapter();
  const pdfBuffer = await pdfAdapter.generateFromHtml(html);

  await auditLog({
    tenantPrisma,
    userId: auth.userId,
    orgId: auth.orgId,
    action: 'EXPORT_PDF',
    resourceType: 'Appointment',
    resourceId: appointmentId,
  });

  return pdfBuffer;
}
