import type { LucideIcon } from 'lucide-react';
import {
  BrainCircuit,
  Database,
  HardDrive,
  KeyRound,
  Mail,
  Mic,
  Server,
  Shield,
  Video,
  Waves,
} from 'lucide-react';

/** One command — no git clone. Pulls divescale images from Docker Hub. */
export const INSTALL_COMMAND =
  'curl -fsSL https://raw.githubusercontent.com/divescale/caremind-deploy-bundle/master/deploy/install.sh | sudo bash';

export const DOCKER_IMAGES = {
  backend: 'divescale/caremind-backend:latest',
  frontend: 'divescale/caremind-frontend:latest',
} as const;

export type LlmProviderId = 'openrouter' | 'openai' | 'anthropic' | 'google';

export const LLM_PROVIDERS: Array<{
  id: LlmProviderId;
  name: string;
  description: string;
  defaultModel: string;
  keyHint: string;
  docsUrl: string;
}> = [
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'Gateway to many models with one API key.',
    defaultModel: 'anthropic/claude-3.5-sonnet',
    keyHint: 'sk-or-...',
    docsUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT-4o and other OpenAI models.',
    defaultModel: 'gpt-4o',
    keyHint: 'sk-...',
    docsUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude models via the Anthropic API.',
    defaultModel: 'claude-3-5-sonnet-20241022',
    keyHint: 'sk-ant-...',
    docsUrl: 'https://console.anthropic.com/settings/keys',
  },
  {
    id: 'google',
    name: 'Google Gemini',
    description: 'Gemini models via Google AI Studio.',
    defaultModel: 'gemini-2.0-flash',
    keyHint: 'AIza...',
    docsUrl: 'https://aistudio.google.com/apikey',
  },
];

export interface PrerequisiteItem {
  icon: LucideIcon;
  title: string;
  description: string;
  items: string[];
}

export const PREREQUISITES: PrerequisiteItem[] = [
  {
    icon: Server,
    title: 'Server',
    description: 'A Linux VM in your VPC with public HTTP/HTTPS access.',
    items: [
      'Ubuntu 22.04+ or Amazon Linux 2023',
      '8 GB RAM minimum (t3.large or larger)',
      '50 GB disk, ports 80 and 443 open',
      'Docker installed automatically by the script',
      'Outbound internet to pull divescale/caremind-* from Docker Hub',
    ],
  },
  {
    icon: Shield,
    title: 'Domain & DNS',
    description: 'A domain or subdomain pointing to your server.',
    items: [
      'A record → your server public IP',
      'Let’s Encrypt email for TLS certificates',
      'Example: caremind.clinic.example.com',
    ],
  },
  {
    icon: Database,
    title: 'Database credentials',
    description: 'PostgreSQL runs in Docker — you choose or auto-generate passwords.',
    items: [
      'Central DB username & password',
      'Tenant DB username & password',
      'Saved in .env for later edits',
    ],
  },
  {
    icon: HardDrive,
    title: 'MinIO storage',
    description: 'Bundled S3-compatible storage for documents and recordings.',
    items: [
      'MinIO access key & secret key',
      'Auto-generated if you use the installer',
    ],
  },
  {
    icon: BrainCircuit,
    title: 'LLM provider',
    description: 'You bring your own API key — choose provider and model.',
    items: [
      'OpenRouter, OpenAI, Anthropic, or Google Gemini',
      'API key and model name',
    ],
  },
  {
    icon: Waves,
    title: 'Voyage AI',
    description: 'Embeddings for document search and AI context.',
    items: ['Voyage API key (pa-...)', 'Default model: voyage-3'],
  },
  {
    icon: Mic,
    title: 'Deepgram',
    description: 'Real-time and batch speech-to-text during consultations.',
    items: ['Deepgram API key'],
  },
  {
    icon: Video,
    title: 'LiveKit',
    description: 'Secure video visits (LiveKit Cloud recommended).',
    items: [
      'LiveKit URL (wss://your-project.livekit.cloud)',
      'API key and API secret',
    ],
  },
  {
    icon: Mail,
    title: 'Email',
    description: 'Transactional email for invites and notifications.',
    items: [
      'Resend (API key + verified from address), or',
      'SMTP host, port, and from address',
    ],
  },
  {
    icon: KeyRound,
    title: 'Auth secrets',
    description: 'JWT secrets are auto-generated by the installer.',
    items: [
      'JWT_SECRET and REFRESH_TOKEN_SECRET',
      'No action needed — stored in .env',
    ],
  },
];

export const WIZARD_STEPS = [
  { id: 'prereqs', label: 'Prerequisites' },
  { id: 'domain', label: 'Domain' },
  { id: 'database', label: 'Database' },
  { id: 'llm', label: 'AI / LLM' },
  { id: 'integrations', label: 'Integrations' },
  { id: 'email', label: 'Email' },
  { id: 'review', label: 'Review' },
] as const;
