import type { LlmProviderId } from './self-host-content';

export interface SelfHostFormValues {
  domain: string;
  acmeEmail: string;
  centralDbUser: string;
  centralDbPassword: string;
  tenantDbUser: string;
  tenantDbPassword: string;
  minioAccessKey: string;
  minioSecretKey: string;
  llmProvider: LlmProviderId;
  llmApiKey: string;
  llmModel: string;
  voyageApiKey: string;
  deepgramApiKey: string;
  livekitUrl: string;
  livekitApiKey: string;
  livekitApiSecret: string;
  emailProvider: 'resend' | 'smtp';
  emailFrom: string;
  resendApiKey: string;
  smtpHost: string;
  smtpPort: string;
  smtpSecure: boolean;
}

export function generateEnvPreview(values: SelfHostFormValues): string {
  const baseUrl = `https://${values.domain}`;

  return `# CareMind self-hosted — configuration preview
# Generated from the setup planner. Run deploy/install.sh on your server
# or paste these values when prompted by the installer.

DOMAIN=${values.domain}
FRONTEND_URL=${baseUrl}
APP_URL=${baseUrl}
ACME_EMAIL=${values.acmeEmail}
VITE_API_BASE_URL=
VITE_LIVEKIT_URL=${values.livekitUrl}

CENTRAL_DB_USER=${values.centralDbUser}
CENTRAL_DB_PASSWORD=${values.centralDbPassword}
CENTRAL_DB_NAME=caremind_central

TENANT_DB_USER=${values.tenantDbUser}
TENANT_DB_PASSWORD=${values.tenantDbPassword}
TENANT_DB_NAME_PREFIX=caremind_tenant_

REDIS_URL=redis://redis:6379

MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_ACCESS_KEY=${values.minioAccessKey}
MINIO_SECRET_KEY=${values.minioSecretKey}
MINIO_USE_SSL=false

JWT_SECRET=<auto-generated-by-installer>
JWT_EXPIRES_IN=15m
REFRESH_TOKEN_SECRET=<auto-generated-by-installer>
REFRESH_TOKEN_EXPIRES_IN=5d

LLM_PROVIDER=${values.llmProvider}
LLM_API_KEY=${values.llmApiKey}
LLM_MODEL=${values.llmModel}

VOYAGE_API_KEY=${values.voyageApiKey}
VOYAGE_MODEL=voyage-3

DEEPGRAM_API_KEY=${values.deepgramApiKey}

LIVEKIT_URL=${values.livekitUrl}
LIVEKIT_API_KEY=${values.livekitApiKey}
LIVEKIT_API_SECRET=${values.livekitApiSecret}

EMAIL_PROVIDER=${values.emailProvider}
EMAIL_FROM=${values.emailFrom}
RESEND_API_KEY=${values.emailProvider === 'resend' ? values.resendApiKey : ''}
SMTP_HOST=${values.emailProvider === 'smtp' ? values.smtpHost : ''}
SMTP_PORT=${values.emailProvider === 'smtp' ? values.smtpPort : ''}
SMTP_SECURE=${values.smtpSecure}
`;
}

export const DEFAULT_FORM_VALUES: SelfHostFormValues = {
  domain: '',
  acmeEmail: '',
  centralDbUser: 'postgres',
  centralDbPassword: '',
  tenantDbUser: 'postgres',
  tenantDbPassword: '',
  minioAccessKey: 'caremind_minio',
  minioSecretKey: '',
  llmProvider: 'openrouter',
  llmApiKey: '',
  llmModel: 'anthropic/claude-3.5-sonnet',
  voyageApiKey: '',
  deepgramApiKey: '',
  livekitUrl: '',
  livekitApiKey: '',
  livekitApiSecret: '',
  emailProvider: 'resend',
  emailFrom: '',
  resendApiKey: '',
  smtpHost: '',
  smtpPort: '587',
  smtpSecure: false,
};
